### ISSUE TITLE
Ieuan sprite is not rendered anymore

### ISSUE THREAD

**Issue by igorko** [igorko/flare-mod-noname#65]
@dorkster could you look into it?

**Comment by dorkster** [comment]
I still see him. Maybe there's a specific map where he's not showing up?

![2015-04-14_164748](https://cloud.githubusercontent.com/assets/913982/7147050/282cc1be-e2c6-11e4-9f57-ace56ae2ca94.png)

**Comment by igorko** [comment]
At the beginning, first two maps.

**Comment by dorkster** [comment]
He appears as normal on both of those maps for me. Do you have any log output?

And in case you're playing on Android, did you forget to run the comment script on noname mod's data files?

**Comment by igorko** [comment]
I'm on Android, and I didn't update data files recently, only executable. It's strange, because all the rest NPCs are ok. I didn't check log, I will look into it asap.

**Comment by igorko** [comment]
Taking in account that
  1. Using different animation file gives sprite to Ieuan
  2 We switched to hw rendering on android
my guess is that we go out of maximum texture size

**Comment by igorko** [comment]
Should be checked but it is mostly https://github.com/dorkster/flare-engine-next/issues/4

**Comment by dorkster** [comment]
Ah, that would make perfect sense. `images/npcs/knight.png` is not packed at all and very wide.

**Comment by igorko** [comment]
SDL/APP ( 3816): SDLHardwareRenderDevice: Couldn't load image: Texture dimensions are limited to 8192x8192

It would be nice to print filename in error message...

**Comment by igorko** [comment]
@stefanbeller IIRC last time it was you who packed spritesheets, can you do this for noname mod?

**Comment by igorko** [comment]
fixed with https://github.com/igorko/flare-mod-noname/commit/e7566b08c622754b190839c4205c62a74f867c95
