### ISSUE TITLE
Protection powers do not have animation

### ISSUE THREAD

**Issue by igorko** [igorko/flare-mod-noname#69]
Some data should be updated because engine changes. Don't know yet what was broken.

**Comment by igorko** [comment]
I have forgot that this power is applied only to allies, so there is no animation on avatar. Maybe on engine side we can show message if no allies are present and do not cast power.

**Comment by igorko** [comment]
@dorkster Can we do something with this? Can we avoid casting if no target is present and show HUD message? (Like for transforms)

**Comment by igorko** [comment]
But we should not lock casting when player clicks on empty place (misses enemy target). We should lock only powers like Protection (when there is no point of using power at all)

**Comment by dorkster** [comment]
`buff_party` powers like Protection don't have targeting. They are applied to all of the player's allies. So I made a [patch](https://github.com/clintbellanger/flare-engine/commit/bd2e624edf1f715d9e27a124e8b588f1c69b60d7) that disables these powers when the player has no allies.
