### ISSUE TITLE
I want to give instructions to the companion who summoned.

### ISSUE THREAD

**Issue by sujiniku** [igorko/flare-mod-noname#79]
The companion who summoned fight enemies with recklessly. But I want the companion to act in accordance with the behavior of the hero fighting or escaping.

There are many enemies, so the hero to escape the,but  companion have fought, then there are many cases where the companion die.

Or, please add the system that the hero to give instructions for the strategy.

Also, I would like to be able to remove companion from the party If necessary.
because I don't want to take weak companion in dangerous place.

**Comment by dorkster** [comment]
Because this would be implemented on the engine side, I've moved it to the flare-engine issue tracker: https://github.com/clintbellanger/flare-engine/issues/1569
